// <auto-generated />
using HelsinkiCityBikeApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelsinkiCityBikeApi.Migrations.Station
{
    [DbContext(typeof(StationContext))]
    [Migration("20230531131927_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("HelsinkiCityBikeApi.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kapasiteet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kaupunki")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operaattor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Osoite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stad")
                        .HasColumnType("TEXT");

                    b.Property<int>("StopId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Xpos")
                        .HasColumnType("REAL");

                    b.Property<float>("Ypos")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });
#pragma warning restore 612, 618
        }
    }
}
